-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "hoursLabel" TEXT NOT NULL DEFAULT 'Lun–Dom 11:30 a 00:00';
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "etaMin" INTEGER NOT NULL DEFAULT 35;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "etaMax" INTEGER NOT NULL DEFAULT 55;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "deliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 80;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "minOrder" DOUBLE PRECISION NOT NULL DEFAULT 250;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "phone" TEXT NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "available" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fulfillment" TEXT NOT NULL DEFAULT 'delivery';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "payment" TEXT NOT NULL DEFAULT 'efectivo';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "schedule" TEXT NOT NULL DEFAULT 'now';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "scheduleTime" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "sizeLabel" TEXT NOT NULL DEFAULT '';

-- CreateTable
CREATE TABLE IF NOT EXISTS "AdminUser" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'admin',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "AdminUser_email_key" ON "AdminUser"("email");
